output "keyvault_name" {
  description = "Name of the keyvault - autogenerated if one is not specified."
  value       = azurerm_key_vault.agw.name
}

output "key_vault_id" {
  description = "Key Vault ID"
  value       = azurerm_key_vault.agw.id
}

output "ssl_secrets" {
  description = "The keyvault secret IDs for the SSL certificate"
  value = {
    for k, v in azurerm_key_vault_certificate.ssl : k => {
      common_name     = v.common_name
      certificate_p12 = v.certificate_p12
    }
  }
}

output "key_vault_identity" {
  description = "The identity created for the AGW to access the key vault"
  value       = azurerm_user_assigned_identity.agw
}