output "keyvault_name" {
  description = "Name of the keyvault - autogenerated if one is not specified."
  value       = azurerm_key_vault.agw.name
}

output "key_vault_id" {
  description = "Key Vault ID"
  value       = azurerm_key_vault.agw.id
}

output "ssl_secrets" {
  description = "The keyvault secret IDs for the SSL certificate"
  value = {
    for k, v in var.ssl_certificates : k => {
      common_name = v.common_name
      secret_id   = azurerm_key_vault_certificate.ssl[k].secret_id
    }
  }
}

output "key_vault_identity" {
  description = "The identity created for the AGW to access the key vault"
  value       = var.user_supplied_agw_identity_id == null ? azurerm_user_assigned_identity.agw[0] : null
}